#management.server.port=9001
#management.endpoints.web.base-path=/monitor
#management.endpoints.web.exposure.include=["*"]?
#management.endpoint.health.show-details=always

spring:
  security:
    user:
      name: admin
      password: 123456
  application:
    name: oauth2-demo
  datasource:
    url: jdbc:mysql://localhost:3306/activiti?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 123456
    driverClassName: com.mysql.cj.jdbc.Driver
#spring.datasource.type = com.zaxxer.hikari.HikariDataSource
#spring.main.allow-bean-definition-overriding =  true

server:
  port: 8081

#eureka.client.service-url.defaultZone=http://localhost:7000/eureka/

mybatis:
  mapperLocations: classpath:mapper/*.xml
# mapper.xml实体类不用写全路径类名
#  type-aliases-package: gxj.study.dal.entity



