
/**用户表 **/
CREATE TABLE `USER` (
    `ID` bigint NOT NULL AUTO_INCREMENT COMMENT 'ID',

    `USER_NAME` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '用户名',
    `PASSWORD` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '密码',
    `STATUS` varchar(255)  DEFAULT NULL COMMENT '用户状态',

--     `DELETE_FLAG` bit(1) DEFAULT NULL COMMENT '是否删除',
    `CREATED_BY` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '创建者',
    `CREATED_AT` TIMESTAMP DEFAULT NULL COMMENT '创建时间',
    `UPDATED_BY` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '修改者',
    `UPDATED_AT` TIMESTAMP DEFAULT NULL COMMENT '修改时间',
    PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='用户';

/**客户端表**/
create table CLIENT_DETAILS (
  `ID` bigint NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `CLIENT_ID` varchar(255) DEFAULT NULL,
  `RESOURCE_IDS` varchar(255) DEFAULT NULL,
  `CLIENT_SECRET` varchar(255) DEFAULT NULL,
  `SCOPE` varchar(255) DEFAULT NULL,
  `AUTHORIZED_GRANT_TYPES` varchar(255) DEFAULT NULL,
  `WEB_SERVER_REDIRECT_URI` varchar(255) DEFAULT NULL,
  `AUTHORITIES` varchar(255) DEFAULT NULL COMMENT 'implicit,client_credentials模式该字段必须要设置对应的权限值，详细见security-oauth2文档说明',
  `ACCESS_TOKEN_VALIDITY` int DEFAULT NULL,
  `REFRESH_TOKEN_VALIDITY` int DEFAULT NULL,
  `ADDITIONAL_INFORMATION` varchar(4096) DEFAULT NULL,
  `AUTOAPPROVE` varchar(255) DEFAULT NULL,
  `DELETE_FLAG` bit(1) DEFAULT NULL COMMENT '是否删除',
  `CREATED_BY` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '创建者',
  `CREATED_AT` timestamp NULL DEFAULT NULL COMMENT '创建时间',
  `UPDATED_BY` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '修改者',
  `UPDATED_AT` timestamp NULL DEFAULT NULL COMMENT '修改时间',
  PRIMARY KEY (`ID`),
  UNIQUE KEY `IDX_CLIENT_ID` (`CLIENT_ID`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='字段说明见spring-security-oauth2官方文档的oauth_client_details表';

/**access_token表**/
create table OAUTH_ACCESS_TOKEN (
#   `ID` bigint NOT NULL AUTO_INCREMENT COMMENT 'ID',
  TOKEN_ID VARCHAR(255),
  TOKEN BLOB,
  AUTHENTICATION_ID VARCHAR(255),
  USER_NAME VARCHAR(255),
  CLIENT_ID VARCHAR(255),
  AUTHENTICATION BLOB,
  REFRESH_TOKEN VARCHAR(255)
);

/**refresh_token表**/
create table OAUTH_REFRESH_TOKEN (
  TOKEN_ID VARCHAR(255),
  TOKEN BLOB,
  AUTHENTICATION BLOB
);


/**客户端模块表**/
create table CLIENT_MODULE (
  `ID` bigint NOT NULL AUTO_INCREMENT COMMENT 'ID',

  `CLIENT_ID` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '客户端代码ID（唯一键，非主键）',
  `NAME` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '模块名',
  `CODE` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '模块代码',
  `DESC` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '描述',

  `CREATED_BY` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '创建者',
  `CREATED_AT` TIMESTAMP DEFAULT NULL COMMENT '创建时间',
  `UPDATED_BY` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '修改者',
  `UPDATED_AT` TIMESTAMP DEFAULT NULL COMMENT '修改时间',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='客户端模块表';

/**客户端接口表**/
create table CLIENT_INTERFACE (
  `ID` bigint NOT NULL AUTO_INCREMENT COMMENT 'ID',

  `CLIENT_ID` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '客户端代码ID（唯一键，非主键）',
  `METHOD` varchar(15) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '请求方式：GET/POST/PUT/DELETE',
  `URL` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '请求路径',
  `DESC` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '描述',

  `CREATED_BY` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '创建者',
  `CREATED_AT` TIMESTAMP DEFAULT NULL COMMENT '创建时间',
  `UPDATED_BY` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '修改者',
  `UPDATED_AT` TIMESTAMP DEFAULT NULL COMMENT '修改时间',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='客户端接口表';


/**客户端授权范围关系表**/
create table CLIENT_SCOPE_REL (
  `ID` bigint NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `TYPE` varchar(15) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '关联类型：MODULE, INTERFACE',
  `REL_ID` bigint DEFAULT NULL COMMENT '关联表(CLIENT_MODULE, CLIENT_INTERFACE)主键',
  `SCOPE` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '授权范围',
  `CREATED_BY` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '创建者',
  `CREATED_AT` TIMESTAMP DEFAULT NULL COMMENT '创建时间',
  `UPDATED_BY` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '修改者',
  `UPDATED_AT` TIMESTAMP DEFAULT NULL COMMENT '修改时间',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='客户端授权范围关系表';


